# 3. Template Matching

In [29]:
# Useful imports
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Loads image of where is waldo
waldo = cv2.imread("./where_is_waldo.jpg")
waldo = cv2.cvtColor(waldo, cv2.COLOR_BGR2RGB)

# Makes a copy of the image
waldo_copy1 = waldo.copy()

# Loads picture of the Charlie's face as a template
template1 = cv2.imread("template1.png")
template1 = cv2.cvtColor(template1, cv2.COLOR_BGR2RGB)

# Gets the width and height of the template image
height1, width1 = template1.shape[0:2]

# Finds the SSD
print(waldo.shape)
print(waldo[0:37, 0:31, 0:3])
ssd = np.sum((waldo[0:37, 0:31, 0:3]-template1[:,:,0:3])**2)


print(ssd)

for x in range(0,27):
    for y in range (0,51)
        ssd = np.sum((waldo[0:37, 0:31, 0:3]-template1[:,:,0:3])**2)

# for patch in waldo[:, :, 0:3].arange(3441).reshape(37,31, 3)
#     ssd = np.sum((patch-template1[:,:,0:3])**2)
#     print(ssd)
    

ssd = np.sum((match1[:,:,0:3]-template1[:,:,0:3])**2)
# Sets a threshold of 0.7 and finds the point that are over the 
# threshold
THRESH1 = 0.7
points1 = np.where(match1 >= THRESH1)

# Draw a cyan rectangle around the match
for point in zip(*points1[::-1]):
    cv2.rectangle(waldo_copy1, point, (point[0]+width1, point[1]+height1), (0,255,255), 5)

# Displays the matched image 
plt.figure(figsize=(20,20))
plt.imshow(waldo_copy1)
plt.title("Matched Image"), plt.xticks([]), plt.yticks([])
plt.show()

(981, 1590, 3)
[[[249 186 207]
  [255 192 213]
  [246 181 201]
  ...
  [ 26  27   0]
  [ 78  89  73]
  [178 196 206]]

 [[251 188 209]
  [255 194 215]
  [247 184 203]
  ...
  [ 59  60  18]
  [ 15  23  10]
  [179 195 210]]

 [[241 180 198]
  [247 186 204]
  [242 181 199]
  ...
  [129 128  82]
  [ 20  26  16]
  [ 61  72  92]]

 ...

 [[135 131 122]
  [ 98  95  86]
  [157 157 147]
  ...
  [ 35  23  25]
  [142 130 130]
  [ 77  67  65]]

 [[ 13  20   0]
  [ 63  70  37]
  [132 142 108]
  ...
  [ 83  72  68]
  [ 80  70  71]
  [ 91  85  89]]

 [[ 68  79  11]
  [ 36  47   0]
  [ 52  65   0]
  ...
  [ 59  46  37]
  [ 20  11  12]
  [ 39  33  43]]]
362046


IndexError: too many indices for array